#pragma config(Sensor, in1,    RLine,          sensorLineFollower)
#pragma config(Sensor, in2,    CLine,          sensorLineFollower)
#pragma config(Sensor, in3,    LLine,          sensorLineFollower)
#pragma config(Sensor, dgtl1,  FREnc,          sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  BLEnc,          sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  REnc,           sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  LEnc,           sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  AEnc,           sensorQuadEncoder)
#pragma config(Motor,  port1,           ABal,          tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port2,           LLift,         tmotorVex393, openLoop)
#pragma config(Motor,  port3,           RLift,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           BLMove,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           FLMove,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           BRMove,        tmotorVex393, openLoop)
#pragma config(Motor,  port7,           FRMove,        tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

/********************
 HEADER DECLARATIONS
 ********************/
void init();
void stdWait();

/***********************
 GLOBAL STATE VARIABLES
 ***********************/

// autoArmBalancer
bool autoBalance = false;

/********
 IMPORTS
 ********/
#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "math.c"
#include "autoBalancer.c"
#include "rc.c"
#include "genMove.c"
#include "move.c"
#include "followLine.c"

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
  init();
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	init();
	StartTask(armBalancer);
	StartTask(rc);

	while(true){
		displayLCDNumber(0, 0, SensorValue[FREnc], 4);
		displayLCDNumber(0, 6, SensorValue[BLEnc], 4);
		displayLCDNumber(0, 12, SensorValue[REnc], 4);
		displayLCDNumber(1, 0, SensorValue[LEnc], 4);
		displayLCDNumber(1, 6, SensorValue[AEnc], 4);


		if(vexRT[Btn7R]){
			StopAllTasks();
		}
		wait1Msec(250);
	}
}


void init(){
	autoBalance = false;
	bLCDBacklight=false;
		clearLCDLine(0);
		clearLCDLine(1);
	SensorValue[FREnc]=0;
	SensorValue[BLEnc]=0;
	SensorValue[LEnc]=0;
	SensorValue[REnc]=0;
	SensorValue[AEnc]=0;
}

void stdWait(){
	wait1Msec(10);
}
